channels:
  status: "1358708060863987743"
  online: "1358708161057390753"

animation:
  loading:
    - "╔🟡 Загрузка."
    - "╔🟡 Загрузка.."
    - "╔🟡 Загрузка..."
  interval: 20
  duration: 120

titles:
  active: "╔🟢 Сервер работает"
  offline: "╔🔴 Сервер выключен"
  online_format: "╚👥 Онлайн: {online}"